### PR TITLE
Use Karma for running tests

### PR DESCRIPTION
**Pull request by randycoulman**
Simplify test-running configuration by adopting Karma.  This has a number of advantages:

* It’s a more standard test-running environment for browser apps
* We don’t need separate test/testDebug configurations
* Chai’s `expect` becomes globally available, so no need to import it everywhere
* We don’t need a top-level `index.js` for tests
* We don’t need a global specHelper
* It enables us to bring in Istanbul for code coverage (coming soon to a PR near you)
* We don’t have to fight issues with DOM infrastructure not being present when running tests on the command-line
* We no longer need to disable the React dev tools to debug tests in the browser
* It should now be possible to use testdouble.js instead of Sinon for mocking/stubbing

Notes:
* We’re not yet sure how this will play in CI; there might be a bit more work to do for that.  We’ll address that when we first need to get that working, so we think it’s out of scope for this PR.

* The assertion output is often not as helpful as that of mocha-webpack.

### CODE REVIEW

**Comment by lexun** [comment]
👍

**Comment by bmatto** [comment]
👍

**Comment by fgarcia** [comment]
@randycoulman I am curious how you test your API responses

I used to have Karma until I started to tape my API calls. Not only because of the speed. It is specially troublesome when the project starts depending on an external API which limits the request rate. Also it reduces the need of a server in testing mode (until one refreshes the recordings)

This requires a Node environment because the recordings need access to the filesystem, but Karma will move everything into the browser

Don't you miss taped HTTP calls when running all tests within a browser?

**Comment by randycoulman** [comment]
@fgarcia We haven't used recorded API calls with our JavaScript apps, though we've done it with Ruby.  On our JS projects, we do most of our unit testing away from the API level.  Sometimes we'll cover the API with some feature/integration tests using something like Capybara.  That works when we control the server and can run it locally.  For testing a third-party API, that wouldn't work well for the reasons you mention.

We've also had some success using [fetch-mock](https://www.npmjs.com/package/fetch-mock) to test our interactions with the API.

**Pull request merged**
