### PR TITLE
Write Architectural Decision Records (ADRs) for major decisions

### PR DESCRIPTION
**Pull request by randycoulman**
This is mostly an experiment with the idea of writing ADRs.  See http://thinkrelevance.com/blog/2011/11/15/documenting-architecture-decisions for an outline of the concept.

It’s somewhat difficult to write these months after the decisions were made, but we’ll do our best to remember the thought process that went into the decisions.

### CODE REVIEW

**Comment by bmatto** [comment]
I think that if we have the ADRs be in separate files that they be timestamped instead of incremented by integers.  A couple of reasons might be...

- 2 people may be creating the same "number" as someone else
- Comparison across projects, so we could see when things happened in different projects.

**Comment by craineum** [comment]
To me this is more documentation than will be needed to get an idea of the code base. Maybe it is not too much for some, but would worry that most wouldn't consume it, and thus make it fairly wasteful.

I also think we have two different types of information:
1. General technologies/frameworks
2. Specific decisions

I could see using a doc like this for the very high level things like React/Rails etc... but then it could just go in the general readme file. @seanculver or @bmatto suggested that we could do a blog post and then link to that as the reasoning. It wouldn't be checked in with the code, but it would be easily readable if someone needed to know more.

Personally I still like the idea of a single ADR file that is either in table or bulleted form. I have added an adrs.md file as an example. Not the easiest to write, but so much easier for someone to quickly get an idea of the codebase. The table forces people to be more concise in their descriptions.

**Comment by randycoulman** [comment]
What I wrote is probably too verbose, but I'm not a fan of the short format.  While constraints are good, that format is too constraining, IMO.

I think there are two purposes for these.  The short format you're proposing addresses one, but the longer format that I proposed addresses the second, and I think that's why we're disagreeing on the format.

One purpose is to get an overview of the technologies being used on a codebase.  The short format would be best for that, but I think even better would be to have that in the README or similar as proposed above.

The other purpose is to provide enough context about the decision to allow someone to revisit the decision in the future in order to have enough information to determine whether it makes sense to reverse the decision.  For that, I think the longer format is better, and I don't think the shorter format has enough information in it.

The other question is what things actually need ADRs.  Perhaps they're not worth it for some of the core technologies in the project.

**Comment by craineum** [comment]
I agree with that. And as such am good with the longer format, just need to lock down what should have ADRs.

**Comment by randycoulman** [comment]
Closing.  We decided that the two ADRs here are more foundational than what should be covered by an ADR.  We'll open a new PR covering other topics in ADRs.

**Pull request closed without merging**
